### PR TITLE
Fix extra indentations on JS scripts

### LINKED ISSUE #49: Javascript spaces instead of tabs
We should use spaces instead of tabs on the JS generation script

### PR DESCRIPTION
**Pull request by gmelodie**
This PR fixes the extra indentations on JS scripts generated by #48. It also makes the autogen scripts more clean and useful. Now you can run them multiple times on the same file without worrying about it making weird changes (I think the fancy word for this is idempotent)

Fixes #49

### CODE REVIEW

File: pages/api-public-metrics-deals-on-chain.tsx [hunk 1]
```diff
@@ -18,26 +18,26 @@ We will be adding more code examples and more details over time. Thanks for bear
...
-                })
-                  .then(data => {
-                    return data.json();
-                  })
-                  .then(data => {
-                    this.setState({ ...data });
-                  });
-              }
+  componentDidMount() {
+    fetch('https://api.estuary.tech/public/metrics/deals-on-chain', {
```
Comment (jimmylee) [inline pages/api-public-metrics-deals-on-chain.tsx:22]: good

File: pages/api-public-miners-deals.tsx [hunk 2]
```diff
@@ -18,26 +18,26 @@ We will be adding more code examples and more details over time. Thanks for bear
...
-                })
-                  .then(data => {
-                    return data.json();
-                  })
-                  .then(data => {
-                    this.setState({ ...data });
-                  });
-              }
+  componentDidMount() {
+    fetch('https://api.estuary.tech/public/miners/deals/{miner}', {
```
Comment (jimmylee) [inline pages/api-public-miners-deals.tsx:22]: good

File: pages/api-public-miners-failures.tsx [hunk 3]
```diff
@@ -18,26 +18,26 @@ We will be adding more code examples and more details over time. Thanks for bear
...
-                })
-                  .then(data => {
-                    return data.json();
-                  })
-                  .then(data => {
-                    this.setState({ ...data });
-                  });
-              }
+  componentDidMount() {
+    fetch('https://api.estuary.tech/public/miners/failures/{miner}?miner=MINER', {
```
Comment (jimmylee) [inline pages/api-public-miners-failures.tsx:22]: good

File: pages/api-public-miners-stats.tsx [hunk 4]
```diff
@@ -18,26 +18,26 @@ We will be adding more code examples and more details over time. Thanks for bear
...
-                })
-                  .then(data => {
-                    return data.json();
-                  })
-                  .then(data => {
-                    this.setState({ ...data });
-                  });
-              }
+  componentDidMount() {
+    fetch('https://api.estuary.tech/public/miners/stats/{miner}', {
```
Comment (jimmylee) [inline pages/api-public-miners-stats.tsx:22]: good

File: pages/api-public-miners.tsx [hunk 5]
```diff
@@ -18,26 +18,26 @@ We will be adding more code examples and more details over time. Thanks for bear
...
-                })
-                  .then(data => {
-                    return data.json();
-                  })
-                  .then(data => {
-                    this.setState({ ...data });
-                  });
-              }
+  componentDidMount() {
+    fetch('https://api.estuary.tech/public/miners', {
```
Comment (jimmylee) [inline pages/api-public-miners.tsx:22]: good

File: pages/api-public-stats.tsx [hunk 6]
```diff
@@ -18,26 +18,26 @@ We will be adding more code examples and more details over time. Thanks for bear
...
-                  })
-                  .then(data => {
-                    this.setState({ ...data });
-                  });
-              }
+  componentDidMount() {
+    fetch('https://api.estuary.tech/public/stats', {
+      method: 'GET',
+      headers: {
+        Authorization: 'Bearer REPLACE_ME_WITH_API_KEY',
```
Comment (jimmylee) [inline pages/api-public-stats.tsx:25]: good

File: pages/collections-commit.tsx [hunk 7]
```diff
@@ -21,26 +21,26 @@ const contents = `[]`;
...
-                })
-                  .then(data => {
-                    return data.json();
-                  })
-                  .then(data => {
-                    this.setState({ ...data });
-                  });
-              }
+  componentDidMount() {
+    fetch('https://api.estuary.tech/collections/{coluuid}/commit', {
```
Comment (jimmylee) [inline pages/collections-commit.tsx:25]: good

File: pages/collections-list-content.tsx [hunk 8]
```diff
@@ -20,26 +20,26 @@ We will be adding more code examples and more details over time. Thanks for bear
...
-                })
-                  .then(data => {
-                    return data.json();
-                  })
-                  .then(data => {
-                    this.setState({ ...data });
-                  });
-              }
+  componentDidMount() {
+    fetch('https://api.estuary.tech/collections/content?coluuid=COLUUID&dir=DIR', {
```
Comment (jimmylee) [inline pages/collections-list-content.tsx:24]: goood

File: pages/collections-list.tsx [hunk 9]
```diff
@@ -18,26 +18,26 @@ We will be adding more code examples and more details over time. Thanks for bear
...
-                })
-                  .then(data => {
-                    return data.json();
-                  })
-                  .then(data => {
-                    this.setState({ ...data });
-                  });
-              }
+  componentDidMount() {
+    fetch('https://api.estuary.tech/collections/list', {
```
Comment (jimmylee) [inline pages/collections-list.tsx:22]: good

File: pages/pinning-add.tsx [hunk 10]
```diff
@@ -29,26 +29,26 @@ const key = 'pinning-add';
...
-                    this.setState({ ...data });
-                  });
-              }
-
-              render() {
-                return <pre>{JSON.stringify(this.state, null, 1)}</pre>;
-              }
-            }`;
+  componentDidMount() {
+    fetch('https://api.estuary.tech/pinning/pins', {
```
Comment (jimmylee) [inline pages/pinning-add.tsx:33]: good

File: pages/pinning-get.tsx [hunk 11]
```diff
@@ -24,26 +24,26 @@ const key = 'pinning-get-by-id';
...
-                    this.setState({ ...data });
-                  });
-              }
-
-              render() {
-                return <pre>{JSON.stringify(this.state, null, 1)}</pre>;
-              }
-            }`;
+  componentDidMount() {
+    fetch('https://api.estuary.tech/pinning/pins/{pinid}', {
```
Comment (jimmylee) [inline pages/pinning-get.tsx:28]: good

File: pages/pinning-list.tsx [hunk 12]
```diff
@@ -29,26 +29,26 @@ const key = 'pinning-list';
...
-                  .then(data => {
-                    this.setState({ ...data });
-                  });
-              }
-
-              render() {
-                return <pre>{JSON.stringify(this.state, null, 1)}</pre>;
-              }
-            }`;
+  componentDidMount() {
```
Comment (jimmylee) [inline pages/pinning-list.tsx:32]: good

File: pages/pinning-remove.tsx [hunk 13]
```diff
@@ -25,26 +25,26 @@ const key = 'pinning-remove';
...
-                    this.setState({ ...data });
-                  });
-              }
-
-              render() {
-                return <pre>{JSON.stringify(this.state, null, 1)}</pre>;
-              }
-            }`;
+  componentDidMount() {
+    fetch('https://api.estuary.tech/pinning/pins/{pinid}', {
```
Comment (jimmylee) [inline pages/pinning-remove.tsx:29]: good

File: pages/pinning-replace.tsx [hunk 14]
```diff
@@ -25,26 +25,26 @@ const key = 'pinning-replace';
...
-                    this.setState({ ...data });
-                  });
-              }
-
-              render() {
-                return <pre>{JSON.stringify(this.state, null, 1)}</pre>;
-              }
-            }`;
+  componentDidMount() {
+    fetch('https://api.estuary.tech/pinning/pins/{pinid}', {
```
Comment (jimmylee) [inline pages/pinning-replace.tsx:29]: good

File: scripts/gen-js-commands.py [hunk 15]
```diff
@@ -8,6 +8,7 @@
 import urllib.request
 from urllib.parse import urlencode
 from pathlib import Path
+from textwrap import dedent
```
Comment (jimmylee) [inline scripts/gen-js-commands.py:11]: lol I see how you did this

File: scripts/update-commands-on-pages.py [hunk 16]
```diff
@@ -46,28 +66,40 @@ def fix_page(filename, page_text):
     # if XMLHttpRequest is not in the file, set code to contents of js_filename
         try:
             with open(js_filename, 'r') as js_file:
-                js_str = js_file.read().strip()
+                js_str = dedent(js_file.read().strip())
```
Comment (jimmylee) [inline scripts/update-commands-on-pages.py:69]: nice

**Review by jimmylee — APPROVED** [review]
LGTM, thanks @gmelodie
